[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[start]
cmd = 'python server.py'

# Fresh Railway service deployment: 2025-09-26-11:40
# Fixed pip installation issue