[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python server.py'

# Force redeploy timestamp: 2025-09-26-10:53
# KeyError fix applied - this file should trigger immediate rebuild