[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python server.py'

# Fresh Railway service deployment: 2025-09-26-11:35
# New service with nuclear fixes applied