services:
  - type: web
    name: transpontual-sistema-frotas
    env: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      pip install -r backend_fastapi/requirements.txt || true && \
      pip install -r flask_dashboard/requirements.txt || true && \
      pip install gunicorn
    startCommand: gunicorn app:app --workers 2 --threads 4 --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile -
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      # Database Configuration (Supabase)
      - key: DATABASE_URL
        value: postgresql://postgres.lijtncazuwnbydeqtoyz:Mariaana953%407334@aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require&connect_timeout=30&options=project%3Dlijtncazuwnbydeqtoyz
      - key: SUPABASE_URL
        value: https://lijtncazuwnbydeqtoyz.supabase.co
      - key: SUPABASE_KEY
        sync: false
      # Security
      - key: JWT_SECRET
        value: kj9q-Xfby-render-prod-2025
      - key: JWT_EXPIRES_MINUTES
        value: 1440
      # Application Configuration
      - key: ENV
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      # Server Configuration
      - key: PORT
        value: 10000
      - key: API_BASE
        value: http://127.0.0.1:8005
      - key: INTERNAL_API_PORT
        value: 8005
      # Python Configuration
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONIOENCODING
        value: utf-8
      # Flask Configuration
      - key: FLASK_SECRET_KEY
        value: render-production-secret-key-2025-supabase
      # CORS Configuration
      - key: ALLOWED_ORIGINS
        value: '["https://transpontual-sistema-frotas.onrender.com", "http://localhost:3000", "*"]'